### PR TITLE
Add slack notification

### PR DESCRIPTION
**Pull request by aschwanb**
A very basic script to post notifications about moved and auto staged packages to slack.

I plan on implementing mail notification too, but I thought I'd send you a first request to see if you like where this is going.

### CODE REVIEW

**Comment by oucsaw** [comment]
Firstly, a million apologies for the delay in getting back to you about this PR: in short, I went on holiday and forgot to finish off my reply. 

Thank you for this feature, which looks helpful. 

Given that slack notifications would be an optional feature for various people (us included at this point, as not everyone loves slack ;-) it might be better to ensure that this was a truly optional feature: currently if I run this version of the code I get an import error:

```
Traceback (most recent call last):
  File "munki-staging.py", line 21, in <module>
    from munkistaging.munki_notify import MunkiNotify
  File "(...)/munki-staging/munkistaging/munki_notify.py", line 18, in <module>
    import slackweb
ImportError: No module named slackweb
```

For the email side of things, it might be nice to be able to configure the sender, as well as the recipient.

Once again, thank you for your interest, and apologies for the delays in getting back to you!

**Comment by aschwanb** [comment]
Welcome back, @oucsaw :-)

I'll have a look at making it completely optional. I think I just have to move some of the logic over to munki-staging.py and do an optional import for slackweb.

In the meantime you could maybe help me out with something:
The notification works great if a pkg gets auto staged or moved by using the **to catalog_name** option. What I'm still struggling with is to get good information on pkgs that are present in munki but not in trello. I would like to include them in the notification too.
How would you go about finding the catalog the trello cards are added to in this loop?

```
for pkg in packagelist.missing_trello_card():
   print "Missing: ", pkg
   pkg.add_trello_card(munki_trello)
```

**Comment by oucsaw** [comment]
Assuming you're happy to be notified after the package has been added to the trello board, something like:

```
for pkg in packagelist.missing_trello_card():
   print "Missing: ", pkg
   pkg.add_trello_card(munki_trello)
      print "Added new trello card for %s to catalog %s using trello list %s" % ( pkg, pkg.trello_catalog.catalog_name, pkg.trello_catalog.list_name )

```

should do the trick. (Or have i mis-understood what you are asking ?)

**Comment by aschwanb** [comment]
That's exactly what I'm after. Thanks 👍

**Comment by aschwanb** [comment]
Closing this as I unfortunately don't have time to work on it right now.

**Pull request closed without merging**
